./counter.sh b_details.txt 				out1.txt 	> b_details_1.txt
./counter.sh disorder_details.txt 		out1.txt 	> disorder_details_1.txt
./counter.sh e_details.txt 				out1.txt 	> e_details_1.txt
./counter.sh fasta_details.txt 			out1.txt 	> fasta_details_1.txt
./counter.sh g_details.txt 				out1.txt 	> g_details_1.txt
./counter.sh h_details.txt 				out1.txt 	> h_details_1.txt
./counter.sh i_details.txt 				out1.txt 	> i_details_1.txt
./counter.sh missing_details.txt 		out1.txt 	> missing_details_1.txt
./counter.sh s_details.txt 				out1.txt 	> s_details_1.txt
./counter.sh t_details.txt 				out1.txt 	> t_details_1.txt
./counter.sh fasta.txt 					out1.txt 	> fasta_1.txt

./counter.sh b_details.txt 				out2.txt 	> b_details_2.txt
./counter.sh disorder_details.txt 		out2.txt 	> disorder_details_2.txt
./counter.sh e_details.txt 				out2.txt 	> e_details_2.txt
./counter.sh fasta_details.txt 			out2.txt 	> fasta_details_2.txt
./counter.sh g_details.txt 				out2.txt 	> g_details_2.txt
./counter.sh h_details.txt 				out2.txt 	> h_details_2.txt
./counter.sh i_details.txt 				out2.txt 	> i_details_2.txt
./counter.sh missing_details.txt 		out2.txt 	> missing_details_2.txt
./counter.sh s_details.txt 				out2.txt 	> s_details_2.txt
./counter.sh t_details.txt 				out2.txt 	> t_details_2.txt
./counter.sh fasta.txt 					out2.txt 	> fasta_2.txt

#./counter.sh b_details.txt 				out3.txt 	> b_details_3.txt
#./counter.sh disorder_details.txt 		out3.txt 	> disorder_details_3.txt
#./counter.sh e_details.txt 				out3.txt 	> e_details_3.txt
#./counter.sh fasta_details.txt 			out3.txt 	> fasta_details_3.txt
#./counter.sh g_details.txt 				out3.txt 	> g_details_3.txt
#./counter.sh h_details.txt 				out3.txt 	> h_details_3.txt
#./counter.sh i_details.txt 				out3.txt 	> i_details_3.txt
#./counter.sh missing_details.txt 		out3.txt 	> missing_details_3.txt
#./counter.sh s_details.txt 				out3.txt 	> s_details_3.txt
#./counter.sh t_details.txt 				out3.txt 	> t_details_3.txt
#./counter.sh fasta.txt 					out3.txt 	> fasta_3.txt

#./counter.sh b_details.txt 				out4.txt 	> b_details_4.txt
#./counter.sh disorder_details.txt 		out4.txt 	> disorder_details_4.txt
#./counter.sh e_details.txt 				out4.txt 	> e_details_4.txt
#./counter.sh fasta_details.txt 			out4.txt 	> fasta_details_4.txt
#./counter.sh g_details.txt 				out4.txt 	> g_details_4.txt
#./counter.sh h_details.txt 				out4.txt 	> h_details_4.txt
#./counter.sh i_details.txt 				out4.txt 	> i_details_4.txt
#./counter.sh missing_details.txt 		out4.txt 	> missing_details_4.txt
#./counter.sh s_details.txt 				out4.txt 	> s_details_4.txt
#./counter.sh t_details.txt 				out4.txt 	> t_details_4.txt
#./counter.sh fasta.txt 					out4.txt 	> fasta_4.txt

#./counter.sh b_details.txt 				out5.txt 	> b_details_5.txt
#./counter.sh disorder_details.txt 		out5.txt 	> disorder_details_5.txt
#./counter.sh e_details.txt 				out5.txt 	> e_details_5.txt
#./counter.sh fasta_details.txt 			out5.txt 	> fasta_details_5.txt
#./counter.sh g_details.txt 				out5.txt 	> g_details_5.txt
#./counter.sh h_details.txt 				out5.txt 	> h_details_5.txt
#./counter.sh i_details.txt 				out5.txt 	> i_details_5.txt
#./counter.sh missing_details.txt 		out5.txt 	> missing_details_5.txt
#./counter.sh s_details.txt 				out5.txt 	> s_details_5.txt
#./counter.sh t_details.txt 				out5.txt 	> t_details_5.txt
#./counter.sh fasta.txt 					out5.txt 	> fasta_5.txt